export const varDescriptions = {
	w1_partnership_status: "Marital/partnership status",
	w1_q34: "Relationship quality",
	w1_sex_frequency: "Sex frequency with partner",
	w1_same_sex_couple: "Same-sex couple",
	w1_ppmsacat: "Urban/rural status",
	w1_ppincimp: "Household income",
	w1_pphhsize: "People in household",
	w1_children_under_18: "Children under 18",
	w1_PPT18OV: "Adults 18+ in household",
	w1_ppwork: "Employment status",
	w1_relate_duration_in2017_years: "Relationship length (years)",
	w1_otherdate_all: "Met others for dating/romance besides partner",
	w1_how_many_all: "How many others met for dating/romance",
	w1_q32: "How met partner online",
	w1_weight_combo: "Survey weight",
	w1_married: "Married",
	w1_ppeduc: "Education level",
	w1_q19: "Living with partner",
	w1_q21a_year: "Year first met partner",
	w1_either_internet_adjusted: "Met partner online",
	w1_q24_internet_dating: "Met partner via dating app/site",
	w1_rel_qual_bucket: "Relationship quality (simplified)",
	w2_rel_qual_bucket: "Relationship quality (simplified)",
	w3_rel_qual_bucket: "Relationship quality (simplified)",
	qual_diff_w1_w2: "Change in relationship quality (2017→2020)",
	qual_diff_w1_w3: "Change in relationship quality (2017→2022)",
	w2_partner_type: "Partnership status",
	w2_relationship_end: "How relationship ended",
	w2_rel_qual_combo: "Relationship quality",
	w2_sex_frequency: "Sex frequency with partner",
	w2_same_sex_couple: "Same-sex couple",
	w2_ppmsacat: "Urban/rural status",
	w2_ppincimp: "Household income",
	w2_pphhsize: "People in household",
	w2_children_under_18: "Children under 18",
	w2_PPT18OV: "Adults 18+ in household",
	w2_ppwork: "Employment status",
	w2_relationship_duration: "Relationship length (years)",
	w2_otherdate_combo: "Met others for dating/romance besides partner",
	w2_how_many_combo: "How many others met for dating/romance",
	w2_Q32: "How met partner online",
	w2_combo_weight: "Survey weight",
	w2_married: "Married",
	w2_ppeduc: "Education level",
	w2_coronavirus_effect_combo: "Pandemic effect on relationship",
	w2_shelter_combo_months: "Months sheltering in place",
	w2_fight: "Arguments with partner (last 7 days)",
	w3_partner_type: "Partnership status",
	w3_relationship_end_combo: "How relationship ended",
	w3_rel_qual: "Relationship quality",
	w3_sex_frequency: "Sex frequency with partner",
	w3_same_sex_couple: "Same-sex couple",
	w3_ppmsacat: "Urban/rural status",
	w3_ppincimp: "Household income",
	w3_pphhsize: "People in household",
	w3_children_under_18: "Children under 18",
	w3_PPT18OV: "Adults 18+ in household",
	w3_ppwork: "Employment status",
	w3_relationship_duration_yrs: "Relationship length (years)",
	w3_otherdate: "Met others for dating/romance",
	w3_how_many: "How many others met for dating/romance",
	w3_Q32: "How met partner online",
	w3_combo_weight: "Survey weight",
	w3_married: "Married",
	w3_ppeduc: "Education level",
	w3_fight: "Arguments with partner (last 7 days)",
	w1_ppage: "Age",
	w1_ppgender: "Gender",
	w1_xlgb: "LGB sample",
	w1_ppethm: "Race / ethnicity",
	w1_relate_duration_bucket: "Relationship length",
	w1_q23_earner: "Who earns more",
	w2_ppage: "Age",
	w2_fight_bucket: "Arguments with partner, last 7 days",
	w2_relationship_duration_bucket: "Relationship length",
	w2_p_monogamy: "Expect partner to be monogamous",
	w2_pandemic_income_bucket: "Pandemic income change",
	w2_Q23_earner: "Who earns more",
	w2_Q32_simple: "Met current partner online",
	w3_ppage: "Age",
	w3_fight_bucket: "Arguments with partner, last 7 days",
	w3_coronavirus_effect_combo: "Pandemic effect on relationship",
	w3_relationship_duration_bucket: "Relationship length",
	w3_vaccine_same: "Partner has same vaccine status",
	w3_COVID_agreement: "COVID safety agreement with partner",
	w3_p_monogamy: "Expect partner to be monogamous",
	w3_monogamy: "Expect self to be monogamous",
	w3_government_response: "Government vaccine mandate view",
	w3_pandemic_income_bucket: "Pandemic income change",
	w3_pandemic_income_collapsed: "Pandemic income change (collapsed)",
	w3_Q23_earner: "Who earns more",
	w3_Q32_simple: "Met current partner online",
	qual_diff_w1_w2_simple: "Relationship change direction (2017→2020)",
	qual_diff_w1_w3_simple: "Relationship change direction (2017→2022)",
	w1_q12: "Partner's political affiliation",
	w1_partyid7: "Respondent's political affiliation",
	w1_political_alignment: "Political alignment with partner",
	w2_Q12_filled: "Partner's political affiliation",
	w2_political_alignment: "Political alignment with partner",
	w3_Q12_filled: "Partner's political affiliation",
	w3_political_alignment: "Political alignment with partner",
	w1_no_friend_overlap: "No prior friend-network overlap",
	w2_no_friend_overlap: "No prior friend-network overlap",
	w3_no_friend_overlap: "No prior friend-network overlap",
	w1_met_through_friend: "Met through friends",
	w2_met_through_friend: "Met through friends",
	w3_met_through_friend: "Met through friends",
	w1_met_through_family: "Met through family",
	w2_met_through_family: "Met through family",
	w3_met_through_family: "Met through family",
	w1_met_as_through_cowork: "Met through work",
	w2_met_as_through_cowork: "Met through work",
	w3_met_as_through_cowork: "Met through work",
	w1_q24_church: "Met through church",
	w2_q24_church: "Met through church",
	w3_q24_church: "Met through church",
};
